### ISSUE TITLE
Best way to install

### ISSUE THREAD

**Issue by AndreGroeschel** [BoundfoxStudios/fluentassertions-unity#1]
Hi Manuel,

first of all thanks for the package. Much better to have something like Fluent Assertions in Unity!
I was wondering what is the best way to install the package since this was not really clear to me. I've put the contents of the tgz package directly inside a folder in the project's package folder. Is there another way to reference the package to not miss out on future updates?

Also, do you have any plans for publishing it on openupm.com? Would be a better flow for updating it and also more people would become aware of this package.

Cheers,
André

**Comment by ManuelRauber** [comment]
Hi André,

I didn't know about openupm.com yet, but it looks good so far. 

I guess, the best thing to do is, to directly publish to the package source instead of having someone manually install the package. 

I will publish it next week to openupm :-)

**Comment by AndreGroeschel** [comment]
Very cool! Thank you :)

**Comment by ManuelRauber** [comment]
Hi @AndreGroeschel,

I've updated the readme to include how the package can be installed. Either via OpenUPM or directly via git.

The package has been published here: https://openupm.com/packages/com.boundfoxstudios.fluentassertions/

I'll close this issue. Please feel free to open another one, if something not working, since that's my first package published to OpenUPM.
