### ISSUE TITLE
Package Importing Errors - for Unity

### ISSUE THREAD

**Issue by EdlenJ** [BoundfoxStudios/fluentassertions-unity#7]
![image](https://user-images.githubusercontent.com/113501464/208861680-8634d6be-c908-4b9d-a292-c57378e46f3a.png)
After Importing the package, a bunch of errors pup ups.

Hoping for a respond. thanks!

**Comment by ManuelRauber** [comment]
> ![image](https://user-images.githubusercontent.com/113501464/208861680-8634d6be-c908-4b9d-a292-c57378e46f3a.png) After Importing the package, a bunch of errors pup ups.
> 
> Hoping for a respond. thanks!

Can you give me some more info?

- Unity Version
- Player Settings regarding .NET settings

Thanks!

**Comment by EdlenJ** [comment]
> 

For this game, I'm using Unity ver. 2020.3.22f1
Player Settings its .NET Standard 2.0
![image](https://user-images.githubusercontent.com/113501464/208914687-d2c324f1-430b-46d7-b171-3b9a635994b9.png)

**Comment by ManuelRauber** [comment]
> > 
> 
> For this game, I'm using Unity ver. 2020.3.22f1 Player Settings its .NET Standard 2.0 ![image](https://user-images.githubusercontent.com/113501464/208914687-d2c324f1-430b-46d7-b171-3b9a635994b9.png)

How did you install the package? 

I just found out that on OpenUPM there is not the new version.

Best would be to directly install it via Unity Package Manage: https://github.com/BoundfoxStudios/fluentassertions-unity#unity-package-manager

**Comment by EdlenJ** [comment]
> > > 
> > 
> > 
> > For this game, I'm using Unity ver. 2020.3.22f1 Player Settings its .NET Standard 2.0 ![image](https://user-images.githubusercontent.com/113501464/208914687-d2c324f1-430b-46d7-b171-3b9a635994b9.png)
> 
> How did you install the package?
> 
> I just found out that on OpenUPM there is not the new version.
> 
> Best would be to directly install it via Unity Package Manage: https://github.com/BoundfoxStudios/fluentassertions-unity#unity-package-manager


![1](https://user-images.githubusercontent.com/113501464/209038775-f0fc25a7-1d06-46aa-b96b-d5f5b770dd7a.PNG)
![2](https://user-images.githubusercontent.com/113501464/209038778-7ecb71c5-d5c2-4481-a66b-f0c8173d46a6.PNG)
![3](https://user-images.githubusercontent.com/113501464/209038785-03340e8e-e28e-41fb-b9dd-fdb61bb2ccc6.PNG)
![4](https://user-images.githubusercontent.com/113501464/209038789-daa40766-7d1a-4a06-98d9-28ce0e78ccd3.PNG)

So again I used to installed it via "Add package from git".
The errors pops up. idk why

**Comment by ManuelRauber** [comment]
@EdlenJ Good news, I know why it happens. Bad news: The latest version will not work with 2020 anymore.
I missed one thing when updating (because I used Unity 2021.2 for creating the package): FluentAssertions uses some syntax only available in C# 9. However, Unity 2020 uses C# 8, so it's not possible to use that version together with the current FluentAssertions version.

I'd recommend not to use Unity 2020 anymore, it will reach end-of-support in mid 2023. 
It would be better to use the current LTS version which is 2021.3. 

Otherwise you may can install an older version of the package and hope for the best.
The documentation how to install a certain version is here: https://docs.unity3d.com/Manual/upm-git.html#revision

So in case of this package, you may can try: https://github.com/BoundfoxStudios/fluentassertions-unity.git#5ce005d465904c3d50b42fe25d27fd4a11f736a2

This is the latest v5.10.3 version of FluentAssertions. I've just tried that out with 2020.3.30f1, at least it compiles. However, you need to add the `NETSTANDARD2_0` define symbol as explained in the Troubleshooting section: https://github.com/BoundfoxStudios/fluentassertions-unity#troubleshooting

**Comment by EdlenJ** [comment]
Ohhh I'll take note.
Thank you.
